//Hey! Here's some of the information I've found and plan to use.

// Use API's:
// https://calendarific.com/holidays/2021/us
//      Remove filler words:
//          for, of, day, global, world, to, international, in, against, last, (Sunday, monday, etc.), the,
//      Grab first two words
//      Show pictures/urls for all upcoming holidays. Set option to specify date.
//
// https://developer.edamam.com/edamam-docs-recipe-api
// https://www.boredapi.com/


//With these API's, we'll have a user specify a date (default = that day). We'll return a holiday to observe, a recipe generated by holiday title as keywords for EDAMAM API, and then use the boredapi to generate a random suggested way to celebrate.
//On days with no holiday, the generator will present the closest holiday.
//Many days have more than one holiday, so it might be beneficial to present a specified number of the soonest approaching holidays, each with their own recipe and suggested activity.
//
//We could, of course, add more qualifiers for each of the API's, but these should start us with a good layout.
//
//I've looked over all of the api's pretty in depth. Hopefully by the time you get back onto the project, I'll have them implemented pretty well.


//API id
let idEdamam = '5d24488a';

//API Keys
let keyEdamam = '174f7baadbf4fc84b1a7b7cf73ba7666';
let keyCalendar = '?api_key=7604e7a55b2d34db7fbdcbdbc25fc170b77c43b6';


//Host
let hostBored = "http://www.boredapi.com/api/activity/";
let hostEdamam = "http://recipepuppy.com/api/";
let hostCalendar = "https://calendarific.com/api/v2/";

//Paths
let pathCalendarHolidays = "holidays";
let pathCalendarCountries = "countries";

//Parameters - default
let paramCalendarCountries = "&country=US";
let paramCalendarYear = "&year=";
let paramCalendarMonth = "&month="





//Begin HTML edit
document.getElementById("weatherSubmit").addEventListener("click", function(event) {
    //prevent empty submit
    event.preventDefault();

    //Get userInput
    const value = encodeURIComponent(document.getElementById("weatherInput").value);
    if (value === "") {
        return;
    }


    //EDAMAM

    const urlEdamam = hostEdamam +



//    //CALENDAR

//    let userYear = "2021"
//    let userMonth = 1;

//    paramCalendarMonth += userMonth.toString(); //default FIXME if statement
//    paramCalendarMonth += "," + (userMonth + 1).toString();
//    paramCalendarYear += "2021"; //default FIXME if statement
//    const urlCalendar = hostCalendar + pathCalendarHolidays + keyCalendar
//        + paramCalendarCountries + paramCalendarYear;
//        // + paramCalendarMonth;

    console.log(url);
    fetch(url)
        .then(function(response) {
            return response.json();
        }).then(function(json) {

            console.log(json);
                         // document.getElementById("weatherResults").innerHTML = results;
        })
        .catch((error) => {console.error(error);} );









//    // Fetch forecast
//    const url = host + imagePath + input /*+ parameters*/ + subscriptionKey;


//    fetch(url2)
//        .then(function(response) {
//            return response.json();
//        }).then(function(json) {

//            console.log(json);

//            //formatting forecast
//            let forecast = "";
//            forecast += "</div>";

//            document.getElementById("forecastResults").innerHTML = forecast;

//        })
//        .catch((error) => {console.error(error);} );









});

